### GET localhost
GET http://localhost:3000/api/cards/

### GET Localhost single entry
GET http://localhost:3000/api/cards/1

### POST
POST http://localhost:3000/api/cards
Content-Type: application/json

{
    "title": "New Post",
    "body": "That's the new post!"
}

### PUT

PUT http://localhost:3000/api/cards/1
Content-Type: application/json

{
    "title": "New Post 2",
    "body": "That's the new post!"
}

### PATCH
PATCH http://localhost:3000/api/cards/2
Content-Type: application/json

{
    "title": "New Post 3",
    "body": "This is my newest post!"
}

### DELETE
DELETE http://localhost:3000/api/cards/2234

### POST jsonplaceholder.com (Create)
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title": "New Post!",
    "body": "This is my post!"
}


### GET jsonplaceholder.com (Read)
GET https://jsonplaceholder.typicode.com/posts


### GET jsonplaceholder.com
GET https://jsonplaceholder.typicode.com/posts/2


### PUT jsonplaceholder.typicode.com (Update)

PUT https://jsonplaceholder.typicode.com/posts/2
Content-Type: application/json

{
    "title": "New Post!",
    "body": "This is my post!"
}


### DELETE jsonplaceholder.com (Delete)
DELETE https://jsonplaceholder.typicode.com/posts/2


### PATCH (Update)

PATCH https://jsonplaceholder.typicode.com/posts/2
Content-Type: application/json

{
    "title": "New Post!",
    "body": "This is my post!"
}
